// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1s03RR5RpOWEfGZJEqoPZtopHtcpAu7E',
    appId: '1:955667405252:web:4d04a530e0b4a92678ac91',
    messagingSenderId: '955667405252',
    projectId: 'chatter-88e2c',
    authDomain: 'chatter-88e2c.firebaseapp.com',
    storageBucket: 'chatter-88e2c.appspot.com',
    measurementId: 'G-GMXW3XVT87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5KZ11MDtPgKjmKFzDjEqFq7ehPkZBOdo',
    appId: '1:955667405252:android:b261d612e6f1f04d78ac91',
    messagingSenderId: '955667405252',
    projectId: 'chatter-88e2c',
    storageBucket: 'chatter-88e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDUgycgmSgGPzG3vBjGGUUqNuMyZh7jI',
    appId: '1:955667405252:ios:fdd56ab1baa4a6e878ac91',
    messagingSenderId: '955667405252',
    projectId: 'chatter-88e2c',
    storageBucket: 'chatter-88e2c.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDUgycgmSgGPzG3vBjGGUUqNuMyZh7jI',
    appId: '1:955667405252:ios:fdd56ab1baa4a6e878ac91',
    messagingSenderId: '955667405252',
    projectId: 'chatter-88e2c',
    storageBucket: 'chatter-88e2c.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1s03RR5RpOWEfGZJEqoPZtopHtcpAu7E',
    appId: '1:955667405252:web:9153b1ad1a09509778ac91',
    messagingSenderId: '955667405252',
    projectId: 'chatter-88e2c',
    authDomain: 'chatter-88e2c.firebaseapp.com',
    storageBucket: 'chatter-88e2c.appspot.com',
    measurementId: 'G-1W3TERTJRK',
  );
}
